### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by krim404** [CyberDNS/hassio-addons-repository#14]
It seems like this addon is somewhere burning a lot of cycles on my system. two whole cores are at 100% all the time.
Is this "normal" behaviour or has it something to do with my system - aka should i start debugging?

-> the process is dotnet Lupusec2Mqtt.dll and it will start to have this high cpu load after a few minutes running

**Comment by CyberDNS** [comment]
I checked the process of my container and it uses between 0 and 10%. I would consider this normal usage because it is constantly polling the lupusec.

To see the resource usage of the lupusec2mqtt container you can run:
``` bash
docker stats $(docker ps -aqf "name=Lupusec2Mqtt")
```

**Comment by krim404** [comment]
well i can see that the very high performance usage comes from the lupusec2mqtt container - and it is only limited by the cpu itself - on a rpi it will use a full core as it will on a intel xeon from 2020

seems like some function is going rouge. as i have some of the less popular lupusec actors, it is possible some of them will result in this behaviour.

sadly i have absolutely no clue from .net, so i dont even know where to start.

**Comment by CyberDNS** [comment]
Ok I see. 
Can you check if the config value for Serilog:MinimumLevel:Default is set to Information, please?

Not that it is logging that the logging in Verbose would use all that power.

**Comment by krim404** [comment]
Just checked that, it is on Information.
It takes about 5 minutes after restart of the integration for this high cpu load.

So here are some information:

replicateable on HAOS as well as on Supervised Docker installation on either X86 as on ARM(aarch64)
Lupusex XT2 after Factory Reset on newest firmware
Installed Actors: door contacts, siren, mini siren, temperature sensors, power switch meter, lightsensor, relais (power as well as shutter), dimmer, water sensor, thermostats, smoke detectors, co detectors, panic button, PIR as well as dual movement detectors

**Comment by xsus95** [comment]
I can not understand the problem. Have the plugin running on a rpi 3b+ and normal workloads. 

![image](https://user-images.githubusercontent.com/55876457/173291004-93bd6a52-3afb-4e77-bd03-9cac12a59f63.png)

**Comment by krim404** [comment]
> I can not understand the problem. Have the plugin running on a rpi 3b+ and normal workloads.
> 
> ![image](https://user-images.githubusercontent.com/55876457/173291004-93bd6a52-3afb-4e77-bd03-9cac12a59f63.png)

25% on a RPI3b is one core at 100%, as it has 4 cores.

**Comment by xsus95** [comment]
> > I can not understand the problem. Have the plugin running on a rpi 3b+ and normal workloads.
> > ![image](https://user-images.githubusercontent.com/55876457/173291004-93bd6a52-3afb-4e77-bd03-9cac12a59f63.png)
> 
> 25% on a RPI3b is one core at 100%, as it has 4 cores.

I didn't consider that, then I agree with you for the screenshot. That was shortly after the start. Currently the plugin works normally and I have the following load with the rpi:

![image](https://user-images.githubusercontent.com/55876457/173342512-7bce060a-ee06-4828-93fa-9c1f6033fbf5.png)

**Comment by krim404** [comment]
sadly my installation will not drop down to lower cpu usage

**Comment by krim404** [comment]
@CyberDNS do you have any idea where i could start debugging?

**Comment by CyberDNS** [comment]
Sorry I have for the moment no other idea how to debug this, do you have still the problem?

Otherwise I will close the issue.

**Comment by krim404** [comment]
Yes, issue is still persistent.

**Comment by CyberDNS** [comment]
I'm working on a new version that replaces the mqtt library and the main poll loop, so probably this will resolve your issue.
When the version >= 3.0.0 is published as stable addon (non-edge), and you still have the problem, please open a new issue under main github project for the lupusec addon: [CyberDNS/Lupusec2Mqtt](https://github.com/CyberDNS/Lupusec2Mqtt)

**Comment by krim404** [comment]
just for your information: the problem indeed has been solved with v3. Thank you very much! :-)

**Comment by CyberDNS** [comment]
Glad to hear that and thank you for the feedback. 🙂
