### ISSUE TITLE
Alarmpanel without function

### ISSUE THREAD

**Issue by tofrie** [CyberDNS/hassio-addons-repository#16]
Hello,

I have a problem getting everything to work. all states are updated. very well done. unfortunately i cannot change the status of the alarm system via the alarm.panel.

**Comment by tofrie** [comment]
Any idea?

**Comment by CyberDNS** [comment]
Hi and sorry for the late reply.

Do you use the stable version or the edge version?
If you are on the stable version is it possible to switch to the edge version to give it a try.

Otherwise, can you provide the logs when doing the operation please?

Best regards,
David

**Comment by CyberDNS** [comment]
Stale
