### ISSUE TITLE
Can you add "vibration detector" to the supported items?

### ISSUE THREAD

**Issue by TiDO2k** [CyberDNS/hassio-addons-repository#17]
Hi,

can you add "vibration detectors" to the integration? If you need anything, please let me know.
Shock sensor (Type 93)

Art.-Nr.:12105
EAN:4260195433885
LUPUSEC - Erschütterungsmelder

Thanks,
best regards,
TiDO

**Comment by CyberDNS** [comment]
Close due to wrong repository.
