### ISSUE TITLE
Lupusec2Mqtt: No such file or directory

### ISSUE THREAD

**Issue by LuckyTriple7** [CyberDNS/hassio-addons-repository#2]
I installed the plug-in in Homeassistant Supervisor and adjusted the config.
after the addon was started, it ends after a few seconds, 

Addon Log:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
/run.sh: line 6: ./Lupusec2Mqtt: No such file or directory
[cmd] /run.sh exited 127
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by CyberDNS** [comment]
Hi,

What architecture you are using? Raspberry, NAS (arm based or intel) or other?
Best regards,
David

**Comment by LuckyTriple7** [comment]
I'm using Raspberry Pi 4 with 32BIT Homeassistant OS

**Comment by CyberDNS** [comment]
Ah looked into all my boxes and I found only a Raspberry Pi 2 which is apparently not compatible with Homeassistant OS.
Do you have the possibility to connect to you Raspberry with ssh and execute "docker images"? If yes can you say what version of the docker image you have, ex. my docker image is: cyberdns/lupusec2mqtt_hassaddon_amd64    1.0.2

**Comment by LuckyTriple7** [comment]
My Docker Image is: **cyberdns/lupusec2mqtt_hassaddon_armv7      1.0.2**

**Comment by CyberDNS** [comment]
I have put a new version 1.0.3 that adds some libraries for ARM architecture.
Can you update and give it a try?

**Comment by LuckyTriple7** [comment]
CMD Docker Image says Version 1.03 now.

Log of the AddOn show an other error mow.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
**/run.sh: line 6:   193 Illegal instruction     (core dumped) ./Lupusec2Mqtt**
[cmd] /run.sh exited 132
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by CyberDNS** [comment]
Thanks. Ok I think I need a Raspberry Pi 3 or 4 do do further testing.
Will come back to you when I have news.

**Comment by CyberDNS** [comment]
Found another way to use the microsoft base images and not the homeassistant ones. 
Now the image is working on my old Rapsberry Pi 2.

I published a new version (1.0.4), you can give it a try.

**Comment by LuckyTriple7** [comment]
Thx, but now i cannot download the Docker Image via Add On Store, Error Message:

Failed to install addon
404 Client Error for http+docker://localhost/v1.40/images/create?tag=1.0.4&fromImage=cyberdns%2Flupusec2mqtt_hassaddon: Not Found ("pull access denied for cyberdns/lupusec2mqtt_hassaddon, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")

**Comment by CyberDNS** [comment]
Yes, my fault. The arch variable was missing in the config.json file.
You can give it another try. Probably you have to uninstall (copy/paste your options) or at least reload the repository.

**Comment by LuckyTriple7** [comment]
Thx, it works now ! Very good :-)
I tested following:
- Alarm Control Panel is working 
- Door / Window Sensors are working

- Motion Sensors are always off in Homeassistant, but i see on the XT2 that there is Motion detected.

![image](https://user-images.githubusercontent.com/60685158/101989579-8e50e700-3ca1-11eb-99dd-458b8e45665b.png)

**Comment by CyberDNS** [comment]
Glad to hear that it is working now. For the motion sensors it is for the moment the "normal" behaviour because I didn't yet finish the status detection (only config).

Probably I will look into it in the next days, I have a lot of motion sensors, too, but I never took the time to integrate them.

I will open a new issue for that on the Lupsec2Mqtt repository.

https://github.com/CyberDNS/Lupusec2Mqtt/issues/6
